 export const hotelData= [

    {
        "hotel_id": 1,
        "chain_id": 421,
        "chain_name": "Samed Resorts Group",
        "brand_id": 0,
        "brand_name": "",
        "hotel_name": "Sai Kaew Beach Resort",
        "hotel_formerly_name": "",
        "hotel_translated_name": "Sai Kaew Beach Resort",
        "addressline1": "8/1 Moo 4 Tumbon Phe Muang",
        "addressline2": "",
        "zipcode": "21160",
        "city": "Koh Samet",
        "state": "Rayong",
        "country": "Thailand",
        "countryisocode": "TH",
        "star_rating": 4,
        "longitude": 101.466979,
        "latitude": 12.568135,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=1",
        "checkin": "2:00 PM",
        "checkout": "11:30 AM",
        "numberrooms": 160,
        "numberfloors": null,
        "yearopened": 2000,
        "yearrenovated": 2018,
        "photo1": "http://pix2.agoda.net/hotelimages/1/-1/0ff4876f93688b8adcbed487b5a2175d.jpg?s=312x",
        "photo2": "http://pix1.agoda.net/hotelimages/1/-1/d821f80943f96ebda33f5a019fa94df4.jpg?s=312x",
        "photo3": "http://pix4.agoda.net/hotelimages/1/-1/59241704e99027895aa6293d734c9fb1.jpg?s=312x",
        "photo4": "http://pix5.agoda.net/hotelimages/1/-1/fce5d70fac02fcb7aa25f31dd25850a8.jpg?s=312x",
        "photo5": "http://pix1.agoda.net/hotelimages/1/-1/7952a908de348304417552246f9039de.jpg?s=312x",
        "overview": "The 4-star Sai Kaew Beach Resort offers comfort and convenience whether you're on business or holiday in Koh Samet. The property features a wide range of facilities to make your stay a pleasant experience. Free Wi-Fi in all rooms, daily housekeeping, gift/souvenir shop, 24-hour front desk, Wi-Fi in public areas are just some of the facilities on offer. Some of the well-appointed guestrooms feature slippers, separate living room, television LCD/plasma screen, mirror, internet access – wireless. Take a break from a long day and make use of fitness center, sauna, outdoor pool, spa, massage. No matter what your reasons are for visiting Koh Samet, Sai Kaew Beach Resort will make you feel instantly at home.",
        "rates_from": 166,
        "continent_id": 2,
        "continent_name": "Asia",
        "city_id": 17222,
        "country_id": 106,
        "number_of_reviews": 3439,
        "rating_average": 8.2,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 6,
        "chain_id": 0,
        "chain_name": "No chain",
        "brand_id": 0,
        "brand_name": "",
        "hotel_name": "Marine Hotel",
        "hotel_formerly_name": "",
        "hotel_translated_name": "Marine Hotel",
        "addressline1": "Sutton Cross",
        "addressline2": "",
        "zipcode": "D13",
        "city": "Dublin",
        "state": "",
        "country": "Ireland",
        "countryisocode": "IE",
        "star_rating": 3,
        "longitude": -6.11034,
        "latitude": 53.38884,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=6",
        "checkin": "3:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": null,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix4.agoda.net/hotelimages/6/6/6_1112201742005261861.jpg?s=312x",
        "photo2": "http://pix2.agoda.net/hotelimages/6/6/6_1201211018006071850.jpg?s=312x",
        "photo3": "http://pix5.agoda.net/hotelimages/6/6/6_0905131455001101926.jpg?s=312x",
        "photo4": "http://pix1.agoda.net/hotelimages/6/6/6_0905131455001101927.jpg?s=312x",
        "photo5": "http://pix4.agoda.net/hotelimages/6/6/6_0905131455001101930.jpg?s=312x",
        "overview": "Marine Hotel is perfectly located for both business and leisure guests in Dublin. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. Free Wi-Fi in all rooms, 24-hour front desk, luggage storage, car park, room service are just some of the facilities on offer. Comfortable guestrooms ensure a good night's sleep with some rooms featuring facilities such as heating, telephone, television, satellite/cable TV, shower. Entertain the hotel's recreational facilities, including sauna, golf course (within 3 km), indoor pool, garden. No matter what your reasons are for visiting Dublin, Marine Hotel will make you feel instantly at home.",
        "rates_from": 144,
        "continent_id": 4,
        "continent_name": "Europe",
        "city_id": 1131,
        "country_id": 188,
        "number_of_reviews": 12,
        "rating_average": 7.4,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 10,
        "chain_id": 29,
        "chain_name": "Melia Hotels International",
        "brand_id": 128,
        "brand_name": "Tryp",
        "hotel_name": "TRYP Malaga Alameda Hotel",
        "hotel_formerly_name": "",
        "hotel_translated_name": "TRYP Malaga Alameda Hotel",
        "addressline1": "Avenida de la Aurora CC.Larios Centro S/N",
        "addressline2": "",
        "zipcode": "29002",
        "city": "Malaga",
        "state": "Andalusia",
        "country": "Spain",
        "countryisocode": "ES",
        "star_rating": 4,
        "longitude": -4.432833,
        "latitude": 36.716057,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=10",
        "checkin": "1:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": 132,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix1.agoda.net/hotelimages/4890100/0/bbdf04328f691e68828c8f49075ace5e.jpg?s=312x",
        "photo2": "http://pix2.agoda.net/hotelimages/10/10/10_14041821020019130452.jpg?s=312x",
        "photo3": "http://pix5.agoda.net/hotelimages/10/10/10_13051721000012487062.jpg?s=312x",
        "photo4": "http://pix5.agoda.net/hotelimages/10/10/10_13051721000012487063.jpg?s=312x",
        "photo5": "http://pix2.agoda.net/hotelimages/10/10/10_13051721010012487064.jpg?s=312x",
        "overview": "TRYP Málaga Alameda Hotel is perfectly located for both business and leisure guests in Malaga. The hotel has everything you need for a comfortable stay. To be found at the hotel are 24-hour room service, free Wi-Fi in all rooms, 24-hour front desk, facilities for disabled guests, Wi-Fi in public areas. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center, sauna. TRYP Málaga Alameda Hotel combines warm hospitality with a lovely ambiance to make your stay in Malaga unforgettable.",
        "rates_from": 83,
        "continent_id": 4,
        "continent_name": "Europe",
        "city_id": 12521,
        "country_id": 167,
        "number_of_reviews": 21,
        "rating_average": 7.5,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 13,
        "chain_id": 227,
        "chain_name": "NH Hotels",
        "brand_id": 451,
        "brand_name": "NH Hotels",
        "hotel_name": "NH Iquique Hotel",
        "hotel_formerly_name": "Radisson Hotel Iquique",
        "hotel_translated_name": "NH Iquique Hotel",
        "addressline1": "Av Costanera 3939",
        "addressline2": "",
        "zipcode": "1111500",
        "city": "Iquique",
        "state": "Tarapacá",
        "country": "Chile",
        "countryisocode": "CL",
        "star_rating": 4,
        "longitude": -70.129991,
        "latitude": -20.269986,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=13",
        "checkin": "3:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": null,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix3.agoda.net/hotelimages/13/0/5f8b6d43a6a287d37bfe1626ab22b0b1.jpg?s=312x",
        "photo2": "http://pix4.agoda.net/hotelimages/13/13/13_15072020190032641184.jpg?s=312x",
        "photo3": "http://pix5.agoda.net/hotelimages/13/13/13_15072020200032641185.jpg?s=312x",
        "photo4": "http://pix1.agoda.net/hotelimages/13/13/13_15072020200032641186.jpg?s=312x",
        "photo5": "http://pix2.agoda.net/hotelimages/13/0/ff8100c85955522a0289e5c71329a17a.jpg?s=312x",
        "overview": "NH Iquique Hotel is perfectly located for both business and leisure guests in Iquique. The hotel offers guests a range of services and amenities designed to provide comfort and convenience. All the necessary facilities, including 24-hour front desk, facilities for disabled guests, Wi-Fi in public areas, car park, room service, are at hand. Guestrooms are designed to provide an optimal level of comfort with welcoming decor and some offering convenient amenities like television LCD/plasma screen, separate living room, air conditioning, heating, wake-up service. To enhance guests' stay, the hotel offers recreational facilities such as fitness center, outdoor pool. A welcoming atmosphere and excellent service are what you can expect during your stay at NH Iquique Hotel.",
        "rates_from": 66,
        "continent_id": 8,
        "continent_name": "South America",
        "city_id": 3527,
        "country_id": 69,
        "number_of_reviews": 5,
        "rating_average": 5.9,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 15,
        "chain_id": 21,
        "chain_name": "Marriott",
        "brand_id": 3821,
        "brand_name": "Sheraton",
        "hotel_name": "Sheraton Grand Hotel & Spa, Edinburgh",
        "hotel_formerly_name": "Sheraton Grand Hotel and Spa Edinburgh",
        "hotel_translated_name": "Sheraton Grand Hotel & Spa, Edinburgh",
        "addressline1": "1 Festival Square",
        "addressline2": "",
        "zipcode": "EH39SR",
        "city": "Edinburgh",
        "state": "Scotland",
        "country": "United Kingdom",
        "countryisocode": "GB",
        "star_rating": 5,
        "longitude": -3.207612,
        "latitude": 55.947063,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=15",
        "checkin": "3:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": 269,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix3.agoda.net/hotelimages/15/0/59a863c3a6e93b759faf2beea910d516.jpg?s=312x",
        "photo2": "http://pix5.agoda.net/hotelimages/15/15/15_13072409510013984463.jpg?s=312x",
        "photo3": "http://pix2.agoda.net/hotelimages/15/15/15_17091312040056285473.jpg?s=312x",
        "photo4": "http://pix4.agoda.net/hotelimages/15/15/15_17091312040056285476.jpg?s=312x",
        "photo5": "http://pix5.agoda.net/hotelimages/15/15/15_17091312040056285477.jpg?s=312x",
        "overview": "Sheraton Grand Hotel & Spa, Edinburgh is perfectly located for both business and leisure guests in Edinburgh. The hotel has everything you need for a comfortable stay. 24-hour room service, free Wi-Fi in all rooms, 24-hour security, daily housekeeping, fireplace are there for guest's enjoyment. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel offers various recreational opportunities. Sheraton Grand Hotel & Spa, Edinburgh is an excellent choice from which to explore Edinburgh or to simply relax and rejuvenate.",
        "rates_from": 185,
        "continent_id": 4,
        "continent_name": "Europe",
        "city_id": 18924,
        "country_id": 107,
        "number_of_reviews": 35,
        "rating_average": 8.8,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 16,
        "chain_id": 496,
        "chain_name": "HK CTS Hotels",
        "brand_id": 4382,
        "brand_name": "Kew Green",
        "hotel_name": "Kew Green Hotel Wanchai Hong Kong",
        "hotel_formerly_name": "Metropark Hotel Wanchai Hong Kong",
        "hotel_translated_name": "Kew Green Hotel Wanchai Hong Kong",
        "addressline1": "41-49 Hennessy Road",
        "addressline2": "",
        "zipcode": "",
        "city": "Hong Kong",
        "state": "Hong Kong",
        "country": "Hong Kong",
        "countryisocode": "HK",
        "star_rating": 4,
        "longitude": 114.170576,
        "latitude": 22.277779,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=16",
        "checkin": "2:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": 173,
        "numberfloors": 18,
        "yearopened": null,
        "yearrenovated": 2007,
        "photo1": "http://pix3.agoda.net/hotelimages/16/16/16_17072912020054755824.jpg?s=312x",
        "photo2": "http://pix5.agoda.net/hotelimages/16/16/16_15121810140038604789.jpg?s=312x",
        "photo3": "http://pix4.agoda.net/hotelimages/16/16/16_13022217540010401585.jpg?s=312x",
        "photo4": "http://pix5.agoda.net/hotelimages/16/16/16_13102910330017213949.jpg?s=312x",
        "photo5": "http://pix5.agoda.net/hotelimages/16/16/16_15121810140038604781.jpg?s=312x",
        "overview": "The 4-star Kew Green Hotel Wanchai Hong Kong offers comfort and convenience whether you're on business or holiday in Hong Kong. Both business travelers and tourists can enjoy the hotel's facilities and services. Service-minded staff will welcome and guide you at the Kew Green Hotel Wanchai Hong Kong. Each guestroom is elegantly furnished and equipped with handy amenities. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center. Friendly staff, great facilities and close proximity to all that Hong Kong has to offer are three great reasons you should stay at Kew Green Hotel Wanchai Hong Kong.",
        "rates_from": 428,
        "continent_id": 2,
        "continent_name": "Asia",
        "city_id": 16808,
        "country_id": 132,
        "number_of_reviews": 4206,
        "rating_average": 8.1,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 17,
        "chain_id": 0,
        "chain_name": "No chain",
        "brand_id": 0,
        "brand_name": "",
        "hotel_name": "Hotel Dann Carlton Medellin",
        "hotel_formerly_name": "",
        "hotel_translated_name": "Hotel Dann Carlton Medellin",
        "addressline1": "Cra 43A No. 7-50",
        "addressline2": "",
        "zipcode": "50001",
        "city": "Medellin",
        "state": "",
        "country": "Colombia",
        "countryisocode": "CO",
        "star_rating": 5,
        "longitude": -75.571053,
        "latitude": 6.20724,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=17",
        "checkin": "3:00 PM",
        "checkout": "1:00 PM",
        "numberrooms": null,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix5.agoda.net/hotelimages/17/17/17_16051513410042341853.jpg?s=312x",
        "photo2": "https://q-xx.bstatic.com/xdata/images/hotel/max500/106650431.jpg?k=5a97e1aef0eef91b1a38caa55387f33ddc2c7e7990291682f4b2928f5b9d7e48&o=",
        "photo3": "http://pix3.agoda.net/hotelimages/17/17/17_0912182150001859572.jpg?s=312x",
        "photo4": "http://pix3.agoda.net/hotelimages/17/17/17_0912182150001859573.jpg?s=312x",
        "photo5": "http://pix5.agoda.net/hotelimages/17/17/17_0912182150001859577.jpg?s=312x",
        "overview": "The 5-star Hotel Dann Carlton Medellín offers comfort and convenience whether you're on business or holiday in Medellin. Both business travelers and tourists can enjoy the hotel's facilities and services. Facilities like 24-hour front desk, facilities for disabled guests, luggage storage, room service, airport transfer are readily available for you to enjoy. Some of the well-appointed guestrooms feature air conditioning, wake-up service, desk, mini bar, alarm clock. Recuperate from a full day of sightseeing in the comfort of your room or take advantage of the hotel's recreational facilities, including fitness center, outdoor pool, spa, massage, steamroom. Friendly staff, great facilities and close proximity to all that Medellin has to offer are three great reasons you should stay at Hotel Dann Carlton Medellín.",
        "rates_from": 78,
        "continent_id": 8,
        "continent_name": "South America",
        "city_id": 10309,
        "country_id": 10,
        "number_of_reviews": 15,
        "rating_average": 8.1,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 18,
        "chain_id": 0,
        "chain_name": "No chain",
        "brand_id": 0,
        "brand_name": "",
        "hotel_name": "Grand Coloane Resort",
        "hotel_formerly_name": "Grand Coloane Beach Resort",
        "hotel_translated_name": "Grand Coloane Resort",
        "addressline1": "1918 Estrada de Hac Sa",
        "addressline2": "",
        "zipcode": "",
        "city": "Macau",
        "state": "Macao",
        "country": "Macau",
        "countryisocode": "MO",
        "star_rating": 5,
        "longitude": 113.576574,
        "latitude": 22.125391,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=18",
        "checkin": "3:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": 208,
        "numberfloors": 8,
        "yearopened": 1993,
        "yearrenovated": 2014,
        "photo1": "http://pix4.agoda.net/hotelimages/18/-1/91c5a3c5d5cc7189b0099fab9a2fbb64.jpg?s=312x",
        "photo2": "http://pix1.agoda.net/hotelimages/18/18/18_15060216180028256873.jpg?s=312x",
        "photo3": "http://pix4.agoda.net/hotelimages/18/18/18_121122143051695.jpg?s=312x",
        "photo4": "http://pix2.agoda.net/hotelimages/18/18/18_121122143052132.jpg?s=312x",
        "photo5": "http://pix2.agoda.net/hotelimages/18/18/18_121122143052678.jpg?s=312x",
        "overview": "Grand Coloane Resort is conveniently located in the popular Coloane area. The hotel offers a wide range of amenities and perks to ensure you have a great time. Take advantage of the hotel's 24-hour room service, daily housekeeping, free Wi-Fi in all rooms, taxi service, 24-hour security. Designed for comfort, selected guestrooms offer television LCD/plasma screen, additional toilet, bathroom phone, carpeting, clothes rack to ensure a restful night. Entertain the hotel's recreational facilities, including hot tub, fitness center, sauna, golf course (on site), outdoor pool. Grand Coloane Resort is an excellent choice from which to explore Macau or to simply relax and rejuvenate.",
        "rates_from": 125,
        "continent_id": 2,
        "continent_name": "Asia",
        "city_id": 21397,
        "country_id": 169,
        "number_of_reviews": 3657,
        "rating_average": 8,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 25,
        "chain_id": 2688,
        "chain_name": "Skycity",
        "brand_id": 3990,
        "brand_name": "Skycity",
        "hotel_name": "SKYCITY Hotel",
        "hotel_formerly_name": "",
        "hotel_translated_name": "SKYCITY Hotel",
        "addressline1": "Corner Victoria & Federal Streets",
        "addressline2": "",
        "zipcode": "1010",
        "city": "Auckland",
        "state": "Auckland",
        "country": "New Zealand",
        "countryisocode": "NZ",
        "star_rating": 4.5,
        "longitude": 174.761966,
        "latitude": -36.848387,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=25",
        "checkin": "3:00 PM",
        "checkout": "11:00 AM",
        "numberrooms": 323,
        "numberfloors": 8,
        "yearopened": 1996,
        "yearrenovated": null,
        "photo1": "http://pix3.agoda.net/hotelimages/25/-1/8dad037385fd554a85e013f931a8a1d5.jpg?s=312x",
        "photo2": "http://pix2.agoda.net/hotelimages/25/25/25_15062308450030331242.jpg?s=312x",
        "photo3": "http://pix5.agoda.net/hotelimages/25/25/25_15062308460030331423.jpg?s=312x",
        "photo4": "http://pix2.agoda.net/hotelimages/25/25/25_15062308460030331424.jpg?s=312x",
        "photo5": "http://pix2.agoda.net/hotelimages/25/25/25_15062308460030331425.jpg?s=312x",
        "overview": "Skycity Hotel is perfectly located for both business and leisure guests in Auckland. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. To be found at the hotel are 24-hour room service, free Wi-Fi in all rooms, wheelchair accessible, casino, 24-hour front desk. Guestrooms are fitted with all the amenities you need for a good night's sleep. In some of the rooms, guests can find television LCD/plasma screen, carpeting, complimentary instant coffee, complimentary tea, mirror. The hotel's peaceful atmosphere extends to its recreational facilities which include fitness center, spa, massage. A welcoming atmosphere and excellent service are what you can expect during your stay at Skycity Hotel.",
        "rates_from": 117,
        "continent_id": 7,
        "continent_name": "Pacific Ocean and Australia",
        "city_id": 3750,
        "country_id": 25,
        "number_of_reviews": 1425,
        "rating_average": 8.5,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 33,
        "chain_id": 3,
        "chain_name": "Accor Hotels",
        "brand_id": 36,
        "brand_name": "Pullman",
        "hotel_name": "Pullman Bordeaux Lac",
        "hotel_formerly_name": "Sofitel Bordeaux Aquitania Hotel",
        "hotel_translated_name": "Pullman Bordeaux Lac",
        "addressline1": "Avenue Jean Gabriel Domergue",
        "addressline2": "",
        "zipcode": "33300",
        "city": "Bordeaux",
        "state": "Aquitaine",
        "country": "France",
        "countryisocode": "FR",
        "star_rating": 4,
        "longitude": -0.565954,
        "latitude": 44.889622,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=33",
        "checkin": "2:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": null,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix3.agoda.net/hotelimages/6584938/0/dc16bcf0fcfe7d2d5110462ebed1705b.jpg?s=312x",
        "photo2": "http://pix3.agoda.net/hotelimages/33/33/33_15022714410025654631.jpg?s=312x",
        "photo3": "http://pix4.agoda.net/hotelimages/33/33/33_17080709240054945185.jpg?s=312x",
        "photo4": "http://pix5.agoda.net/hotelimages/33/33/33_17080709240054945186.jpg?s=312x",
        "photo5": "http://pix3.agoda.net/hotelimages/33/33/33_17080709240054945187.jpg?s=312x",
        "overview": "Located in Le Lac, Pullman Bordeaux Lac is a perfect starting point from which to explore Bordeaux. Offering a variety of facilities and services, the hotel provides all you need for a good night's sleep. Casino, 24-hour front desk, facilities for disabled guests, luggage storage, Wi-Fi in public areas are just some of the facilities on offer. Each guestroom is elegantly furnished and equipped with handy amenities. To enhance guests' stay, the hotel offers recreational facilities such as fitness center, golf course (within 3 km), outdoor pool, massage, solarium. Pullman Bordeaux Lac is an excellent choice from which to explore Bordeaux or to simply relax and rejuvenate.",
        "rates_from": 136,
        "continent_id": 4,
        "continent_name": "Europe",
        "city_id": 12838,
        "country_id": 153,
        "number_of_reviews": 21,
        "rating_average": 8.2,
        "rates_currency": "USD"
      },
      {
        "hotel_id": 34,
        "chain_id": 0,
        "chain_name": "No chain",
        "brand_id": 0,
        "brand_name": "",
        "hotel_name": "Hotel Conde Luna",
        "hotel_formerly_name": "",
        "hotel_translated_name": "Hotel Conde Luna",
        "addressline1": "Avenida Independencia, 7",
        "addressline2": "",
        "zipcode": "24003",
        "city": "Leon",
        "state": "",
        "country": "Spain",
        "countryisocode": "ES",
        "star_rating": 4,
        "longitude": -5.57119,
        "latitude": 42.596451,
        "url": "https://www.agoda.com/partners/partnersearch.aspx?hid=34",
        "checkin": "2:00 PM",
        "checkout": "12:00 PM",
        "numberrooms": null,
        "numberfloors": null,
        "yearopened": null,
        "yearrenovated": null,
        "photo1": "http://pix3.agoda.net/hotelimages/34/34/34_08091300010079.jpg?s=312x",
        "photo2": "http://pix5.agoda.net/hotelimages/34/34/34_1001231702002566194.jpg?s=312x",
        "photo3": "http://pix5.agoda.net/hotelimages/34/34/34_0912031414001753274.jpg?s=312x",
        "photo4": "http://pix5.agoda.net/hotelimages/34/34/34_0912031414001753275.jpg?s=312x",
        "photo5": "http://pix5.agoda.net/hotelimages/34/34/34_0912190835001951320.jpg?s=312x",
        "overview": "Stop at Hotel Conde Luna to discover the wonders of Leon. Both business travelers and tourists can enjoy the hotel's facilities and services. 24-hour front desk, luggage storage, room service, meeting facilities, babysitting are on the list of things guests can enjoy. Some of the well-appointed guestrooms feature air conditioning, heating, wake-up service, desk, mini bar. Entertain the hotel's recreational facilities, including massage. No matter what your reasons are for visiting Leon, Hotel Conde Luna will make you feel instantly at home.",
        "rates_from": 75,
        "continent_id": 4,
        "continent_name": "Europe",
        "city_id": 7609,
        "country_id": 167,
        "number_of_reviews": 10,
        "rating_average": 8.5,
        "rates_currency": "USD"
      },
]